# Generated by Django 4.1.4 on 2023-01-20 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaapp', '0002_cinema_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cinema',
            new_name='Movie',
        ),
    ]
